spring.application.name=inventario-service
server.port=8083

# Base de Datos RDS PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentSchema=inventario
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=inventario
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Seguridad Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER}
app.cognito.client-id=${COGNITO_CLIENT_ID}